### PR TITLE
commit new database config & package

### PR DESCRIPTION
**Pull request by fadlifz**
1. Add database config
2. Add package entity & model

### CODE REVIEW

**Comment by fadlifz** [comment]
good

**Review by fadlifz — COMMENTED** [review]
good

**Review by fadlifz — COMMENTED** [review]
enough

**Review by fadlifz — COMMENTED** [review]
good

**Comment by fadlifz** [comment]
good

**Comment by fadlifz** [comment]
tes

**Comment by fadlifz** [comment]
tes

**Review by fadlifz — COMMENTED** [review]
good

**Comment by mohafadli** [comment]
good

**Review by mohafadli — APPROVED** [review]

**Pull request merged**
